name: Build and Push Docker Image

on:
  push:
    tags:
      - 'v*'  # Déclenche sur les tags commençant par 'v' (ex: v1.0.0)
      - '*.*.*'  # Déclenche aussi sur les tags de type semver (ex: 1.0.0)

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Extract tag name
        id: extract_tag
        run: echo "tag=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT

      - name: Login to Private Registry
        uses: docker/login-action@v3
        with:
          registry: registry.frely.fr
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            registry.frely.fr/vacprint:${{ steps.extract_tag.outputs.tag }}
            registry.frely.fr/vacprint:latest
          cache-from: type=registry,ref=registry.frely.fr/vacprint:buildcache
          cache-to: type=registry,ref=registry.frely.fr/vacprint:buildcache,mode=max
          platforms: linux/amd64

      - name: Image digest
        run: echo "Image pushed successfully with tag ${{ steps.extract_tag.outputs.tag }}"
